version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/src/server/main.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
